//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int idArticulo { get; set; }
        public Nullable<decimal> Sku { get; set; }
        public string Articulo1 { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public decimal idDepartamento { get; set; }
        public decimal idClase { get; set; }
        public decimal idFamilia { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descontinuado { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    }
}
