//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        public decimal idFamilia { get; set; }
        public string NombreFamilia { get; set; }
        public decimal idClase { get; set; }
    
        public virtual Clase Clase { get; set; }
    }
}
